Revert "qcom-multimedia-image: Add gst-plugins-imsdk"
Reverts #149, it broke qcom-armv7a builds with:

ERROR: Nothing RPROVIDES 'gst-plugins-imsdk-oss-meta' (but
/work/build/../meta-qcom-distro/recipes-products/images/qcom-multimedia-image.bb
RDEPENDS on or otherwise requires it)\n", 'gst-plugins-imsdk RPROVIDES
gst-plugins-imsdk-oss-meta but was skipped: incompatible with machine
qcom-armv7a (not in COMPATIBLE_MACHINE)\n', "ERROR: Required build
target 'qcom-multimedia-image' has no buildable providers.\n", "Missing
or unbuildable dependency chain was: ['qcom-multimedia-image',
'gst-plugins-imsdk-oss-meta

Signed-off-by: Dmitry Baryshkov <dmitry.baryshkov@oss.qualcomm.com>