ci/yocto-check-layer.sh: use meta-lts-mixins layer
Without the meta-lts-mixins layer being referenced in the dependecy
chain, the yocto-check-layer fails with the missing dependecy error,
because lately meta-qcom started to depend on the layer. Add layer to
the dependencies list.

ERROR: Layer meta-qcom depends on lts-linux-firmware-mixin and isn't found.

Signed-off-by: Dmitry Baryshkov <dmitry.baryshkov@oss.qualcomm.com>