pipewire: backport patches to build with glibc 2.43
Building pipewire with glibc 2.43 causes errors:

| ../sources/pipewire-1.6.2/spa/plugins/alsa/acp/compat.h:437:13: error: assignment discards 'const' qualifier from pointer target type [-Werror=discarded-qualifiers]
|   437 |     if ((fn = strrchr(p, PA_PATH_SEP_CHAR)))
|       |             ^

Backport upstream patches to fix.

This should be reverted once it's merged in meta-multimedia.

Link: https://lists.openembedded.org/g/openembedded-devel/message/125376

Signed-off-by: Anuj Mittal <anuj.mittal@oss.qualcomm.com>